apiVersion: apps/v1
kind: Deployment
metadata:
    name: orleans-silo8
    labels:
        app: kubesilo
spec:
    replicas: 2
    selector:
        matchLabels:
            app: kubesilo
    template:
        metadata:
            labels:
                app: kubesilo
        spec:
            serviceAccountName: orleanssilo
            containers:
                - name: orleanssilo8
                  image: silo:dev8
                  imagePullPolicy: Never
